#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

CONFIG_BACKUP="/tmp/dsa_project01_config_backup_$$.txt"
GENERATOR_BIN="/tmp/dsa_project01_data_generator_$$"
MAIN_BIN="/tmp/dsa_project01_main_$$"
OUTPUT_FILE="/tmp/dsa_project01_main_output_$$.txt"
SMOKE_DATASET="dataset_smoke.csv"

restore_config() {
    if [[ -f "$CONFIG_BACKUP" ]]; then
        cp "$CONFIG_BACKUP" config.txt
    fi
}

trap restore_config EXIT

assert_file_exists() {
    local path="$1"
    if [[ ! -f "$path" ]]; then
        echo "FAIL: expected file '$path' to exist" >&2
        exit 1
    fi
}

assert_output_contains() {
    local needle="$1"
    if ! grep -Fq "$needle" "$OUTPUT_FILE"; then
        echo "FAIL: expected main output to contain: $needle" >&2
        echo "---- main output ----" >&2
        cat "$OUTPUT_FILE" >&2
        echo "---------------------" >&2
        exit 1
    fi
}

cp config.txt "$CONFIG_BACKUP"

cat > config.txt <<'CONFIG'
# Generated by tests/smoke_pipeline.sh
dataset_file=dataset_smoke.csv
generated_record_count=25
query_count=5
data_sizes=10,25
range_threshold=20
range_small=3
range_large=5
index_prefix=smoke_index_
CONFIG

echo "[1/5] Building data generator..."
g++ data_generator.cpp -o "$GENERATOR_BIN"

echo "[2/5] Generating small dataset..."
"$GENERATOR_BIN"
assert_file_exists "$SMOKE_DATASET"

LINE_COUNT="$(wc -l < "$SMOKE_DATASET")"
if [[ "$LINE_COUNT" -ne 26 ]]; then
    echo "FAIL: expected $SMOKE_DATASET to contain 26 lines, got $LINE_COUNT" >&2
    exit 1
fi

HEADER="$(head -n 1 "$SMOKE_DATASET")"
if [[ "$HEADER" != "ID,Payload" ]]; then
    echo "FAIL: expected CSV header 'ID,Payload', got '$HEADER'" >&2
    exit 1
fi

echo "[3/5] Building main program..."
g++ Solution/main.cpp Solution/bplus_tree.cpp -o "$MAIN_BIN"

echo "[4/5] Running main program with smoke config..."
"$MAIN_BIN" > "$OUTPUT_FILE"

echo "[5/5] Checking pipeline output..."
assert_output_contains "Dataset file: dataset_smoke.csv"
assert_output_contains "Query count: 5"
assert_output_contains "Prepared benchmark file name: smoke_index_10.dat"
assert_output_contains "Prepared benchmark file name: smoke_index_25.dat"

echo "PASS: smoke pipeline completed successfully."
